name: .NET Test

on:
  push:
    branches: [ main ]
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.gitea/workflows/publish-*.yaml'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: https://github.com/actions/setup-dotnet@v3
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults-9.x"

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-9.x
        path: TestResults-9.x
        if: ${{ always() }}
        retention-days: 30
